version: '3.8'

services:
  vue-cv:
    container_name: vue-cv
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "${PORT}:${PORT}"
    networks:
      - vue-cv
    env_file:
      - .env

networks:
  vue-cv:
    driver: bridge